{
    'name': 'GST Livelink Packaging',
    'version': '3.0.1',
    'author': 'Guadaltech S.L.',
    'license': 'GPL-3',
    'category': '',
    'depends': [
        'mrp',
        'mrp_workorder',
        'stock'
    ],
    'data': [
            'security/ir.model.access.csv',
            'reports/paperformat_serial_number_pack_soy.xml',
            'reports/report_serial_number_pack_soy.xml',
            'reports/paperformat_serial_number_pack_soy_again.xml',
            'reports/report_serial_number_pack_soy_again.xml',
            'reports/report_packaging_paperformat.xml',
            'reports/report_stock_packaging_and_qr.xml',
            'reports/report_stock_production_lot_paperformat.xml',
            'reports/report_packaging.xml',
            'reports/report_stock_production_lot.xml',
            'reports/report_qr_again_paperformat.xml',
            'reports/report_qr_again_template.xml',
            'reports/report_packaging_again.xml',
            'reports/report_packaging_paperformat_again.xml',
            'views/product_template_view.xml',
            'views/mrp_routing_work_view.xml',
            'views/mrp_workorder_views.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
